### ISSUE TITLE
Exception Errors - Fails to Run

### ISSUE THREAD

**Issue by zrodriguez89** [HumanBehaviourChangeProject/Info-extract#4]
I downloaded the project and attempted to run it from the command line following the instructions. After running:

`mvn exec:java@indexer`

I get the following errors (see attached images). I checked to make sure everything was up to date. The first image is the error without full stack trace of errors. The second image is the same command re-run with more details on the errors (i.e. trace).

<img width="1439" alt="error hbcp" src="https://user-images.githubusercontent.com/30937144/72288304-c32e6700-3616-11ea-825c-6242dd30e56d.png">

<img width="1439" alt="-e full error hbcp" src="https://user-images.githubusercontent.com/30937144/72288310-c6295780-3616-11ea-8587-92d9d6a8c56e.png">

**Comment by charlesjochim** [comment]
Try running `mvn compile -U` to compile the code before indexing the PDFs with the command you used above.
There was another problem with the code you downloaded, so you should update the code before compiling and indexing.

**Comment by zrodriguez89** [comment]
It works after doing that and stepping through the listed commands. However when getting to `mvn exec:java@predict` I got a null pointer exception.

<img width="1423" alt="desktop" src="https://user-images.githubusercontent.com/30937144/73129577-77d06d00-3fb5-11ea-8e61-d8921a6973de.png">

Also when looking at the javadoc, I was wondering how to retrieve study attributes from the command line while in the top directory. Also how to input new pdfs from the command line.

**Comment by charlesjochim** [comment]
We are going to have a new release soon (should be within the next week or so) and I think it would be easiest to wait for that, which solves these problems.  I will let you know when that is available.

**Comment by zrodriguez89** [comment]
Sounds good. Thanks!

**Comment by charlesjochim** [comment]
A new release is now available and hopefully the documentation for getting started is a bit clearer.  Please open a new issue if you have trouble though.  Thanks!
